import feladatok
eredmeny: int = feladatok.fel1(6, 16)
print(eredmeny)
negativ_db: int = feladatok.fel2()
print(f"A negatív számok száma: {negativ_db}")
eredmeny2: int = feladatok.fel3(6, 16)
print(eredmeny2)
randomOsszeg: int = feladatok.fel4()
print(randomOsszeg)
legnagyobb: int = feladatok.fel5()
print(legnagyobb)
#atlag: float = feladatok.fel6()
#print(atlag)
bekertAtlag: int = feladatok.fel7()
print(bekertAtlag)
